#!/bin/zsh
export VAULTPATH=${0:a:h}

export ANSIBLE_VAULT_PASSWORD_FILE=${VAULTPATH}/.vault
export ANSIBLE_INVENTORY=${VAULTPATH}/inventory


# Redis Fact Cache
export ANSIBLE_CACHE_PLUGIN=redis
export ANSIBLE_CACHE_PLUGIN_CONNECTION=127.0.0.1:6379
#export ANSIBLE_CACHE_PLUGIN_CONNECTION=10.0.10.152:6379
export ANSIBLE_CACHE_PLUGIN_PREFIX=fact_

# JSON File Fact Cache
#export ANSIBLE_CACHE_PLUGIN=jsonfile
#export ANSIBLE_CACHE_PLUGIN_CONNECTION=fact_cache

# YAML File Fact Cache
#export ANSIBLE_CACHE_PLUGIN=yaml
#export ANSIBLE_CACHE_PLUGIN_CONNECTION=fact_cache


# Inventory Cache
#export ANSIBLE_INVENTORY_CACHE=True
#export ANSIBLE_INVENTORY_CACHE_PLUGIN=redis
#export ANSIBLE_INVENTORY_CACHE_PLUGIN_CONNECTION=10.0.10.152:6379
#export ANSIBLE_INVENTORY_CACHE_PLUGIN_PREFIX=inventory_
