---
docker_containers:
  mycroft:
    description: "Mycroft Voice Assistant"
    image: mycroftai/docker-mycroft:latest
    network_mode: host
    ports:
      - '8181:8181'
    devices:
      - '/dev/snd:/dev/snd'
    volumes:
      - '{{ automation_mounted_directory }}/configs/mycroft:/root/.mycroft'
      - '/etc/localtime:/etc/localtime:ro'

telegraf_plugins_extra:
  - name: docker
    options:
      endpoint: "unix:///var/run/docker.sock"
      timeout: "5s"
      perdevice: "true"
      total: "true"
