---
telegraf_plugins_extra:
  - name: docker
    options:
      endpoint: "unix:///var/run/docker.sock"
      timeout: "5s"
      perdevice: "true"
      total: "true"
  - name: postgresql
    options:
      address: "postgres://postgres:{{ vault_postgres_password }}@localhost"
      ignored_databases:
        - template0
        - template1

docker_containers:
  postgres:
    description: "Postgres DB"
    image: postgres
    env:
      PUID: '0'
      PGID: '0'
      VERSION: 'latest'
      POSTGRES_PASSWORD: '{{ vault_postgres_password }}'
      POSTGRES_DB: '{{ postgres_default_db }}'
    ports:
      - '5432:5432'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/var/lib/postgresql/data:/var/lib/postgresql/data'
