---

docker_containers:
  jenkins:
    description: "Jenkins CI/CD server"
    image: "jenkins/jenkins:lts"
    network_mode: host
    volumes:
      - "{{ jenkins_config_directory }}:/var/jenkins_home"
      - "{{ data_mount_root }}/{{ git_directory }}:/git"
    ports:
      - 8080:8080
      - 50000:50000
  docker_registry:
    description: "Artifactory/Repository"
    image: "registry:2"
    volumes:
      - "{{ docker_registry_config_directory }}:/var/lib/registry"
    ports:
      - 9000:50000