netplan_configuration:
  network:
    version: 2
    ethernets:
      eth0:
        match:
          macaddress: "{{ ansible_eth0.macaddress }}"
        mtu: "{{ ansible_eth0.mtu }}"
        set-name: eth0
      eth1:
        match:
          macaddress: "{{ ansible_eth1.macaddress }}"
        mtu: "{{ ansible_eth0.mtu }}"
        set-name: eth1
    bonds:
      bond0:
        interfaces:
          - eth0
          - eth1
        macaddress: "{{ ansible_default_ipv4.macaddress }}"
        mtu: "{{ ansible_default_ipv4.mtu }}"
        parameters:
          down-delay: 0
          lacp-rate: fast
          mii-monitor-interval: 100
          mode: 802.3ad
          transmit-hash-policy: layer3+4
          up-delay: 0
    bridges:
      br0:
        addresses:
          - "{{ (ansible_default_ipv4.address + '/' + ansible_default_ipv4.netmask | string) | ipaddr('host/prefix') }}"
        gateway4: "{{ ansible_default_ipv4.gateway }}"
        interfaces:
          - bond0
        macaddress: "{{ ansible_default_ipv4.macaddress }}"
        mtu: "{{ ansible_default_ipv4.mtu }}"
        nameservers:
          addresses:
            - "{{ ansible_default_ipv4.gateway }}"
          search: "{{ ansible_dns.search }}"
        parameters:
          forward-delay: 0
          stp: false
telegraf_plugins_extra:
  - name: docker
    options:
      endpoint: "unix:///var/run/docker.sock"
      timeout: "5s"
      perdevice: "true"
      total: "true"
