telegraf_plugins_extra:
  - name: docker
    options:
      endpoint: "unix:///var/run/docker.sock"
      timeout: "5s"
      perdevice: "true"
      total: "true"
## EdgeSwitch CPU Utilization
  - name: exec
    options:
      commands:
        - "/etc/telegraf/telegraf.d/scripts/edgeswitch_load.sh 192.168.0.5"
        - "/etc/telegraf/telegraf.d/scripts/edgeswitch_load.sh 192.168.0.6"
        - "/etc/telegraf/telegraf.d/scripts/edgeswitch_load.sh 192.168.0.7"
      timeout: "1s"
      interval: "5s"
      data_format: "influx"
## Ubiquiti AP Devices
  - name: snmp
    options:
      name: "snmp.UAP"
      agents:
        - "192.168.0.101"
        - "192.168.0.102"
        - "192.168.0.104"
      interval: "10s"
      timeout: "10s"
      retries: 3
      version: 2
      community: "public"
      max_repetitions: 1
  - name: snmp.field
    options:
      is_tag: "true"
      name: "sysName"
      oid: "RFC1213-MIB::sysName.0"
  - name: snmp.field
    options:
      name: "sysObjectID"
      oid: "RFC1213-MIB::sysObjectID.0"
  - name: snmp.field
    options:
      name: "sysDescr"
      oid: "RFC1213-MIB::sysDescr.0"
  - name: snmp.field
    options:
      name: "sysContact"
      oid: "RFC1213-MIB::sysContact.0"
  - name: snmp.field
    options:
      name: "sysLocation"
      oid: "RFC1213-MIB::sysLocation.0"
  - name: snmp.field
    options:
      name: "sysUpTime"
      oid: "RFC1213-MIB::sysUpTime.0"
  - name: snmp.field
    options:
      name: "unifiApSystemModel"
      oid: "UBNT-UniFi-MIB::unifiApSystemModel"
  - name: snmp.field
    options:
      name: "unifiApSystemVersion"
      oid: "UBNT-UniFi-MIB::unifiApSystemVersion"
  - name: snmp.field
    options:
      name: "memTotal"
      oid: "FROGFOOT-RESOURCES-MIB::memTotal.0"
  - name: snmp.field
    options:
      name: "memFree"
      oid: "FROGFOOT-RESOURCES-MIB::memFree.0"
  - name: snmp.field
    options:
      name: "memBuffer"
      oid: "FROGFOOT-RESOURCES-MIB::memBuffer.0"
  - name: snmp.field
    options:
      name: "memCache"
      oid: "FROGFOOT-RESOURCES-MIB::memCache.0"
  - name: snmp.table
    options:
      oid: "IF-MIB::ifTable"
  - name: snmp.table.field
    options:
      is_tag: "true"
      oid: "IF-MIB::ifDescr"
  - name: snmp.table
    options:
      oid: "UBNT-UniFi-MIB::unifiRadioTable"
  - name: snmp.table.field
    options:
      is_tag: "true"
      oid: "UBNT-UniFi-MIB::unifiRadioName"
  - name: snmp.table.field
    options:
      is_tag: "true"
      oid: "UBNT-UniFi-MIB::unifiRadioRadio"
  - name: snmp.table
    options:
      oid: "UBNT-UniFi-MIB::unifiVapTable"
  - name: snmp.table.field
    options:
      is_tag: "true"
      oid: "UBNT-UniFi-MIB::unifiVapName"
  - name: snmp.table.field
    options:
      is_tag: "true"
      oid: "UBNT-UniFi-MIB::unifiVapRadio"
  - name: snmp.table
    options:
      oid: "UBNT-UniFi-MIB::unifiIfTable"
  - name: snmp.table.field
    options:
      is_tag: "true"
      oid: "UBNT-UniFi-MIB::unifiIfName"
  - name: snmp.table
    options:
      oid: "FROGFOOT-RESOURCES-MIB::loadTable"
  - name: snmp.table.field
    options:
      is_tag: "true"
      oid: "FROGFOOT-RESOURCES-MIB::loadDescr"
  - name: snmp.field
    options:
      name: "snmpInPkts"
      oid: "SNMPv2-MIB::snmpInPkts.0"
  - name: snmp.field
    options:
      name: "snmpInGetRequests"
      oid: "SNMPv2-MIB::snmpInGetRequests.0"
  - name: snmp.field
    options:
      name: "snmpInGetNexts"
      oid: "SNMPv2-MIB::snmpInGetNexts.0"
  - name: snmp.field
    options:
      name: "snmpInTotalReqVars"
      oid: "SNMPv2-MIB::snmpInTotalReqVars.0"
  - name: snmp.field
    options:
      name: "snmpInGetResponses"
      oid: "SNMPv2-MIB::snmpInGetResponses.0"
  - name: snmp.field
    options:
      name: "snmpOutPkts"
      oid: "SNMPv2-MIB::snmpOutPkts.0"
  - name: snmp.field
    options:
      name: "snmpOutGetRequests"
      oid: "SNMPv2-MIB::snmpOutGetRequests.0"
  - name: snmp.field
    options:
      name: "snmpOutGetNexts"
      oid: "SNMPv2-MIB::snmpOutGetNexts.0"
  - name: snmp.field
    options:
      name: "snmpOutGetResponses"
      oid: "SNMPv2-MIB::snmpOutGetResponses.0"
## EdgeRouter devices
  - name: snmp
    options:
      name: "snmp.EdgeOS"
      agents:
        - "192.168.0.5"
        - "192.168.0.6"
        - "192.168.0.7"
      interval: "30s"
      timeout: "15s"
      retries: 3
      version: 2
      community: "public"
      max_repetitions: 1
      fielddrop:
        - "laErrorFlag"
        - "laErrMessage"
#      tagdrop:
#        diskIODevice:
#          - "loop*"
#          - "ram*"
  - name: snmp.field
    options:
      name: "sysName"
      oid: "SNMPv2-MIB::sysName.0"
      is_tag: "true"
  #  System vendor OID
  - name: snmp.field
    options:
      name: "sysObjectID"
      oid: "SNMPv2-MIB::sysObjectID.0"
  #  System description
  - name: snmp.field
    options:
      name: "sysDescr"
      oid: "ENTITY-MIB::entPhysicalModelName.2"
  #  System Firmware
  - name: snmp.field
    options:
      name: "emSoftwareRev"
      oid: "ENTITY-MIB::entPhysicalSoftwareRev.1"
  #  System Serial
  - name: snmp.field
    options:
      name: "emSerialNum"
      oid: "ENTITY-MIB::entPhysicalSerialNum.1"
  ## Host/System Resources
  #  System uptime
  - name: snmp.field
    options:
      name: "sysUpTime"
      oid: "iso.3.6.1.2.1.1.3.0"

  ## System Memory (physical/virtual)

  # Total Mem
  - name: snmp.field
    options:
      name: "fpMemAvailable"
      oid: "1.3.6.1.4.1.4413.1.1.1.1.4.2.0"
  # Free Mem
  - name: snmp.field
    options:
      name: "fpMemFree"
      oid: "1.3.6.1.4.1.4413.1.1.1.1.4.1.0"

  ## Interface metrics
  #  Per-interface traffic, errors, drops
  - name: snmp.table
    options:
      oid: "IF-MIB::ifTable"
  - name: snmp.table.field
    options:
      oid: "IF-MIB::ifName"
      is_tag: "true"
  - name: snmp.table
    options:
      oid: "IF-MIB::ifXTable"
  - name: snmp.table.field
    options:
      oid: "IF-MIB::ifAlias"
      is_tag: "true"
  - name: snmp.table.field
    options:
      oid: "IF-MIB::ifName"
      is_tag: "true"

  ## SNMP metrics
  #  Number of SNMP messages received
  - name: snmp.field
    options:
      name: "snmpInPkts"
      oid: "SNMPv2-MIB::snmpInPkts.0"
  #  Number of SNMP Get-Request received
  - name: snmp.field
    options:
      name: "snmpInGetRequests"
      oid: "SNMPv2-MIB::snmpInGetRequests.0"
  #  Number of SNMP Get-Next received
  - name: snmp.field
    options:
      name: "snmpInGetNexts"
      oid: "SNMPv2-MIB::snmpInGetNexts.0"
  #  Number of SNMP objects requested
  - name: snmp.field
    options:
      name: "snmpInTotalReqVars"
      oid: "SNMPv2-MIB::snmpInTotalReqVars.0"
  #  Number of SNMP Get-Response received
  - name: snmp.field
    options:
      name: "snmpInGetResponses"
      oid: "SNMPv2-MIB::snmpInGetResponses.0"
  #  Number of SNMP messages sent
  - name: snmp.field
    options:
      name: "snmpOutPkts"
      oid: "SNMPv2-MIB::snmpOutPkts.0"
  #  Number of SNMP Get-Request sent
  - name: snmp.field
    options:
      name: "snmpOutGetRequests"
      oid: "SNMPv2-MIB::snmpOutGetRequests.0"
  #  Number of SNMP Get-Next sent
  - name: snmp.field
    options:
      name: "snmpOutGetNexts"
      oid: "SNMPv2-MIB::snmpOutGetNexts.0"
  #  Number of SNMP Get-Response sent
  - name: snmp.field
    options:
      name: "snmpOutGetResponses"
      oid: "SNMPv2-MIB::snmpOutGetResponses.0"
